"""
food_info.py - Food AI Assistant
Dữ liệu thông tin chi tiết cho 35 món ăn Việt Nam.
Đã chuẩn hóa vung_mien nghiêm ngặt về ba nhóm: 'Miền Bắc', 'Miền Trung', 'Miền Nam'
Bổ sung đầy đủ 3 trường bắt buộc cho toàn bộ 35 món: vung_mien, vi_dac_trung, cach_an.
Trường calo luôn đảm bảo định dạng số sạch để regex tìm kiếm chính xác.
"""

FOOD_DB = {
    "Banh Flan": {
        "ten_hien_thi": "Bánh flan",
        "mo_ta": "Bánh trứng sữa mềm mịn phủ caramel, món tráng miệng ngọt ngào vô cùng phổ biến tại Việt Nam.",
        "vung_mien": "Miền Nam",
        "vi_dac_trung": "Ngọt, Béo",
        "cach_an": "Ăn trực tiếp khi lạnh, có thể thêm đá bào hoặc một chút cà phê đen lên trên bề mặt để tăng hương vị.",
        "calo": "180 kcal / phần",
        "khau_phan": "1 phần (~100g)",
        "protein": "4g",
        "carb": "22g",
        "fat": "8g",
        "thanh_phan": "Trứng gà, sữa tươi, sữa đặc, đường caramel",
        "gia_trung_binh": "10.000 - 25.000 VNĐ",
        "thoi_diem_phu_hop": "Tráng miệng",
        "chi_so_suc_khoe": "⭐⭐⭐☆☆",
        "khuyen_nghi": "Hạn chế dùng nếu đang kiểm soát đường huyết hoặc trong chế độ ăn kiêng khắt khe."
    },
    "Banh beo": {
        "ten_hien_thi": "Bánh bèo",
        "mo_ta": "Bánh hấp từ bột gạo mỏng mịn trong chén nhỏ, ăn kèm tôm chấy, mỡ hành và da heo chiên giòn.",
        "vung_mien": "Miền Trung",
        "vi_dac_trung": "Đậm, Thanh",
        "cach_an": "Rưới nước mắm chua ngọt trực tiếp vào từng chén bánh bèo nhỏ, dùng thìa tre mỏng múc ăn nóng.",
        "calo": "80 kcal / chén",
        "khau_phan": "1 chén bánh",
        "protein": "2g",
        "carb": "15g",
        "fat": "1g",
        "thanh_phan": "Bột gạo, tôm chấy, mỡ hành, hành phi, da heo giòn",
        "gia_trung_binh": "5.000 - 10.000 VNĐ",
        "thoi_diem_phu_hop": "Ăn vặt, ăn nhẹ",
        "chi_so_suc_khoe": "⭐⭐⭐⭐☆",
        "khuyen_nghi": "Món ăn ít chất béo, rất thích hợp làm món ăn nhẹ xế chiều."
    },
    "Banh bot loc": {
        "ten_hien_thi": "Bánh bột lọc",
        "mo_ta": "Bánh bột năng trong suốt dai dai, nhìn rõ nhân tôm đỏ và thịt ba chỉ rim đậm đà bên trong.",
        "vung_mien": "Miền Trung",
        "vi_dac_trung": "Đậm, Thanh",
        "cach_an": "Chấm kèm nước mắm chua ngọt pha loãng, có thể thêm vài lát ớt xắt để tăng vị cay nồng đặc trưng miền Trung.",
        "calo": "55 kcal / cái",
        "khau_phan": "1 cái bánh",
        "protein": "2g",
        "carb": "10g",
        "fat": "1g",
        "thanh_phan": "Bột năng, tôm tươi rim, thịt ba chỉ, lá chuối gói bánh",
        "gia_trung_binh": "3.000 - 7.000 VNĐ",
        "thoi_diem_phu_hop": "Ăn vặt, ăn nhẹ",
        "chi_so_suc_khoe": "⭐⭐⭐⭐☆",
        "khuyen_nghi": "Nên ăn kèm các loại rau sống để bổ sung thêm chất xơ cho cơ thể."
    },
    "Banh can": {
        "ten_hien_thi": "Bánh căn",
        "mo_ta": "Bánh đổ trong khuôn đất nung nhỏ, nướng chín vàng giòn ráo dầu, ăn kèm với trứng hoặc hải sản.",
        "vung_mien": "Miền Trung",
        "vi_dac_trung": "Thanh, Béo",
        "cach_an": "Thả ngập bánh vào bát nước chấm mắm nêm hoặc nước mắm xíu mại ấm nóng cùng rất nhiều hành lá băm.",
        "calo": "70 kcal / cái",
        "khau_phan": "1 cái bánh",
        "protein": "3g",
        "carb": "8g",
        "fat": "3g",
        "thanh_phan": "Bột gạo tẻ, trứng cút hoặc trứng gà, mực, tôm, hành lá",
        "gia_trung_binh": "5.000 - 10.000 VNĐ",
        "thoi_diem_phu_hop": "Ăn sáng, ăn tối",
        "chi_so_suc_khoe": "⭐⭐⭐⭐☆",
        "khuyen_nghi": "Nên ăn kèm nhiều đu đủ bào và rau sống để đỡ ngán."
    },
    "Banh canh": {
        "ten_hien_thi": "Bánh canh",
        "mo_ta": "Sợi bánh canh to dày làm từ bột gạo hoặc bột lọc, chan nước dùng sền sệt ninh từ xương heo và hải sản ngọt thanh.",
        "vung_mien": "Miền Nam",
        "vi_dac_trung": "Đậm, Béo",
        "cach_an": "Dùng nóng, vắt thêm chanh tươi, bỏ thêm ớt băm và ăn kèm với quẩy nóng hoặc rau sống tùy vùng.",
        "calo": "420 kcal / tô",
        "khau_phan": "1 tô nóng",
        "protein": "20g",
        "carb": "55g",
        "fat": "12g",
        "thanh_phan": "Sợi bánh canh, giò heo, cua, tôm, chả cá, nước dùng xương hầm",
        "gia_trung_binh": "35.000 - 60.000 VNĐ",
        "thoi_diem_phu_hop": "Bữa ăn chính",
        "chi_so_suc_khoe": "⭐⭐⭐⭐☆",
        "khuyen_nghi": "Bổ sung thêm rau cải, giá đỗ để cân bằng tinh bột và chất xơ."
    },
    "Banh chung": {
        "ten_hien_thi": "Bánh chưng",
        "mo_ta": "Món bánh chưng xanh truyền thống ngày Tết gói bằng lá dong, thể hiện sự hòa quyện của đất trời.",
        "vung_mien": "Miền Bắc",
        "vi_dac_trung": "Đậm, Béo",
        "cach_an": "Bóc lớp lá dong, dùng lạt cắt bánh thành từng miếng đều nhau, ăn kèm hành muối, củ kiệu hoặc rán vàng giòn.",
        "calo": "250 kcal / 100g",
        "khau_phan": "1 phần 100g",
        "protein": "6g",
        "carb": "40g",
        "fat": "7g",
        "thanh_phan": "Gạo nếp cái hoa vàng, đậu xanh cà vỏ, thịt ba chỉ heo, hạt tiêu, lá dong",
        "gia_trung_binh": "50.000 - 120.000 VNĐ",
        "thoi_diem_phu_hop": "Bữa ăn chính",
        "chi_so_suc_khoe": "⭐⭐⭐☆☆",
        "khuyen_nghi": "Không nên ăn quá nhiều xôi nếp vào buổi tối muộn để tránh đầy bụng."
    },
    "Banh gio": {
        "ten_hien_thi": "Bánh giò",
        "mo_ta": "Món bánh hấp hình chóp làm từ bột tẻ thanh mát, nhân bên trong là thịt heo băm xào mộc nhĩ thơm nức.",
        "vung_mien": "Miền Bắc",
        "vi_dac_trung": "Đậm, Béo",
        "cach_an": "Ăn khi bánh còn bốc khói nóng hổi, có thể dùng thìa xúc trực tiếp kèm chả lụa, giò tai, dưa góp và tương ớt.",
        "calo": "320 kcal / cái",
        "khau_phan": "1 cái bánh lớn",
        "protein": "10g",
        "carb": "42g",
        "fat": "12g",
        "thanh_phan": "Bột gạo tẻ, thịt heo xay, mộc nhĩ, hành khô, lá chuối",
        "gia_trung_binh": "15.000 - 30.000 VNĐ",
        "thoi_diem_phu_hop": "Ăn sáng, ăn nhẹ xế chiều",
        "chi_so_suc_khoe": "⭐⭐⭐☆☆",
        "khuyen_nghi": "Nên ăn kèm đồ chua để trung hòa lượng mỡ béo trong nhân thịt."
    },
    "Banh khot": {
        "ten_hien_thi": "Bánh khọt",
        "mo_ta": "Bánh chiên giòn rụm trong khuôn nhỏ, phủ một lớp nước cốt dừa béo ngậy cùng tôm tươi và bột tôm đỏ đẹp mắt.",
        "vung_mien": "Miền Nam",
        "vi_dac_trung": "Đậm, Béo",
        "cach_an": "Cuộn chặt bánh khọt nóng hổi vào lá xà lách, cải bẹ xanh cùng rau thơm rồi chấm ngập trong mắm chua ngọt.",
        "calo": "400 kcal / phần",
        "khau_phan": "1 phần 8 bánh",
        "protein": "15g",
        "carb": "35g",
        "fat": "20g",
        "thanh_phan": "Bột gạo, tôm tươi, nước cốt dừa, hành lá băm, bột nghệ",
        "gia_trung_binh": "30.000 - 60.000 VNĐ",
        "thoi_diem_phu_hop": "Ăn vặt, ăn xế",
        "chi_so_suc_khoe": "⭐⭐⭐☆☆",
        "khuyen_nghi": "Bánh chiên nhiều dầu mỡ nên cần ăn kèm một lượng lớn rau sống để bổ sung chất xơ."
    },
    "Banh mi": {
        "ten_hien_thi": "Bánh mì",
        "mo_ta": "Món ăn đường phố biểu tượng nổi tiếng toàn cầu của Việt Nam, vỏ giòn rụm ruột xốp mềm.",
        "vung_mien": "Miền Nam",
        "vi_dac_trung": "Đậm, Béo",
        "cach_an": "Dùng trực tiếp ngay khi vỏ còn nóng giòn rụm để cảm nhận sự hòa quyện của pate béo và thịt nguội đậm vị.",
        "calo": "400 kcal / ổ",
        "khau_phan": "1 ổ đầy đủ",
        "protein": "15g",
        "carb": "45g",
        "fat": "15g",
        "thanh_phan": "Bột mì, pate heo, bơ trứng, thịt nguội, giò chả, đồ chua, ngò rí, dưa leo",
        "gia_trung_binh": "20.000 - 50.000 VNĐ",
        "thoi_diem_phu_hop": "Ăn sáng, ăn nhanh",
        "chi_so_suc_khoe": "⭐⭐⭐☆☆",
        "khuyen_nghi": "Có thể giảm bớt bơ béo và sốt nếu bạn đang thực hiện chế độ giảm cân."
    },
    "Banh pia": {
        "ten_hien_thi": "Bánh pía",
        "mo_ta": "Đặc sản nức tiếng Sóc Trăng với lớp vỏ xếp nhiều tầng cực mỏng, ôm trọn nhân sầu riêng, đậu xanh bùi béo.",
        "vung_mien": "Miền Nam",
        "vi_dac_trung": "Ngọt, Béo",
        "cach_an": "Dùng dao cắt nhỏ bánh thành các miếng vừa ăn, thưởng thức chậm rãi và nhấp cùng ngụm trà nóng chát nhẹ.",
        "calo": "420 kcal / cái",
        "khau_phan": "1 cái bánh lớn",
        "protein": "7g",
        "carb": "60g",
        "fat": "17g",
        "thanh_phan": "Bột mì, sầu riêng tươi, đậu xanh, mỡ heo, lòng đỏ trứng muối",
        "gia_trung_binh": "15.000 - 40.000 VNĐ",
        "thoi_diem_phu_hop": "Ăn vặt, tráng miệng cùng trà",
        "chi_so_suc_khoe": "⭐⭐☆☆☆",
        "khuyen_nghi": "Lượng calo và đường rất cao, không khuyến nghị cho người tiểu đường hoặc béo phì."
    },
    "Banh tet": {
        "ten_hien_thi": "Bánh tét",
        "mo_ta": "Món bánh nếp gói lá chuối hình trụ tròn đầy đặn, nét đẹp ẩm thực cổ truyền ngày Tết phương Nam.",
        "vung_mien": "Miền Nam",
        "vi_dac_trung": "Đậm, Béo",
        "cach_an": "Dùng tước dây lạt chuối để khoanh bánh cắt gọn thành từng lát tròn, ăn kèm dưa kiệu ngọt cay hoặc củ cải ngâm mắm.",
        "calo": "290 kcal / 100g",
        "khau_phan": "1 khoanh bánh 100g",
        "protein": "7g",
        "carb": "45g",
        "fat": "9g",
        "thanh_phan": "Gạo nếp thơm, đậu xanh giã nhuyễn, thịt ba rọi mỡ, lá chuối tươi",
        "gia_trung_binh": "50.000 - 150.000 VNĐ",
        "thoi_diem_phu_hop": "Bữa ăn chính",
        "chi_so_suc_khoe": "⭐⭐⭐☆☆",
        "khuyen_nghi": "Độ dẻo nếp cao có thể gây nóng trong, nên cân nhắc lượng ăn vừa đủ."
    },
    "Banh trang nuong": {
        "ten_hien_thi": "Bánh tráng nướng",
        "mo_ta": "Được mệnh danh là 'Pizza Việt Nam', bánh nướng trên than hồng thơm lừng với vô vàn topping rực rỡ.",
        "vung_mien": "Miền Nam",
        "vi_dac_trung": "Đậm, Béo",
        "cach_an": "Ăn nóng ngay khi vừa nhấc khỏi vỉ nướng than, gập đôi hoặc dùng kéo cắt nhỏ, xịt thêm tương ớt và sốt mayonnaise béo ngậy.",
        "calo": "380 kcal / cái",
        "khau_phan": "1 cái cỡ lớn",
        "protein": "14g",
        "carb": "40g",
        "fat": "18g",
        "thanh_phan": "Bánh tráng mỏng, trứng cút hoặc trứng gà, khô bò sợi, hành lá băm, tôm khô, phô mai",
        "gia_trung_binh": "15.000 - 35.000 VNĐ",
        "thoi_diem_phu_hop": "Ăn vặt phố xá về chiều",
        "chi_so_suc_khoe": "⭐⭐⭐☆☆",
        "khuyen_nghi": "Chứa khá nhiều gia vị mặn ngọt và chất béo bơ dầu, không nên ăn thay bữa chính."
    },
    "Banh uot": {
        "ten_hien_thi": "Bánh ướt",
        "mo_ta": "Lớp bánh tráng bột gạo hấp siêu mỏng ướt mềm mại, ăn kèm chả lụa thơm và hành phi giòn tan.",
        "vung_mien": "Miền Nam",
        "vi_dac_trung": "Đậm, Thanh",
        "cach_an": "Trải đều bánh lên đĩa, xếp chả lụa, nem chua, dưa leo băm nhỏ rồi rưới nước mắm chua ngọt thanh dịu.",
        "calo": "320 kcal / phần",
        "khau_phan": "1 đĩa đầy đủ",
        "protein": "12g",
        "carb": "55g",
        "fat": "6g",
        "thanh_phan": "Bột gạo tẻ, chả lụa, giá đỗ hấp, hành phi vàng giòn, rau thơm thái nhuyễn",
        "gia_trung_binh": "20.000 - 40.000 VNĐ",
        "thoi_diem_phu_hop": "Ăn sáng, ăn nhẹ",
        "chi_so_suc_khoe": "⭐⭐⭐⭐☆",
        "khuyen_nghi": "Bánh không chiên dầu mỡ trực tiếp nên rất nhẹ bụng và dễ tiêu hóa."
    },
    "Banh xeo": {
        "ten_hien_thi": "Bánh xèo",
        "mo_ta": "Bánh đúc chiên chảo lớn mỏng giòn rụm ánh vàng từ nghệ, ôm trọn phần nhân tôm thịt ngọt tươi.",
        "vung_mien": "Miền Nam",
        "vi_dac_trung": "Đậm, Béo",
        "cach_an": "Tước một góc bánh nóng xèo xèo, cuộn cùng xà lách cải bẹ xanh, lá cát lồi rồi chấm sâu trong bát nước mắm chua ngọt.",
        "calo": "450 kcal / cái",
        "khau_phan": "1 cái bánh lớn",
        "protein": "18g",
        "carb": "40g",
        "fat": "24g",
        "thanh_phan": "Bột gạo pha nước cốt dừa và nghệ, thịt ba chỉ, tôm đất, giá đỗ, đậu xanh",
        "gia_trung_binh": "25.000 - 60.000 VNĐ",
        "thoi_diem_phu_hop": "Bữa ăn chính, bữa tối",
        "chi_so_suc_khoe": "⭐⭐⭐☆☆",
        "khuyen_nghi": "Hãy ăn thật nhiều lá rau rừng đi kèm để bổ sung vitamin hỗ trợ tiêu dầu mỡ."
    },
    "Banh_Duc": {
        "ten_hien_thi": "Bánh đúc",
        "mo_ta": "Món ăn mộc mạc dân dã làm từ bột gạo quấy đặc dẻo quánh, phủ ngập thịt băm mộc nhĩ xào đậm vị.",
        "vung_mien": "Miền Bắc",
        "vi_dac_trung": "Đậm, Thanh",
        "cach_an": "Múc bánh đúc dẻo quánh nóng hổi ra bát tô sâu, chan nước mắm ấm pha ngọt thơm nhè nhẹ và ăn nóng ngay.",
        "calo": "180 kcal / phần",
        "khau_phan": "1 bát ấm nóng",
        "protein": "4g",
        "carb": "35g",
        "fat": "2g",
        "thanh_phan": "Bột gạo, thịt heo băm, mộc nhĩ, hành khô phi, nước mắm ngọt ấm",
        "gia_trung_binh": "10.000 - 25.000 VNĐ",
        "thoi_diem_phu_hop": "Ăn vặt buổi xế chiều",
        "chi_so_suc_khoe": "⭐⭐⭐⭐☆",
        "khuyen_nghi": "Ít calo và béo, thích hợp sưởi ấm dạ dày những ngày thời tiết trở lạnh."
    },
    "Bun mam": {
        "ten_hien_thi": "Bún mắm",
        "mo_ta": "Đặc sản Nam Bộ đậm sắc hương với nước dùng đặc trưng nấu cốt từ mắm cá linh, mắm cá sặc biển sông mênh mông.",
        "vung_mien": "Miền Nam",
        "vi_dac_trung": "Đậm, Cay",
        "cach_an": "Ăn lúc cực kỳ nóng hổi để dậy hương mắm thơm nồng nàn, thả vào các loại rau đồng quê như bông súng, hẹ, rau đắng.",
        "calo": "550 kcal / tô",
        "khau_phan": "1 tô đầy đủ",
        "protein": "30g",
        "carb": "60g",
        "fat": "18g",
        "thanh_phan": "Bún tươi, mắm cốt sặc/linh, thịt heo quay giòn da, mực tươi, tôm, cà tím",
        "gia_trung_binh": "40.000 - 80.000 VNĐ",
        "thoi_diem_phu_hop": "Bữa trưa, bữa tối chính",
        "chi_so_suc_khoe": "⭐⭐⭐☆☆",
        "khuyen_nghi": "Hàm lượng muối mặn của cốt mắm khá cao, người cao huyết áp nên hạn chế húp hết nước lèo."
    },
    "Bun_Bo_Hue": {
        "ten_hien_thi": "Bún bò Huế",
        "mo_ta": "Tinh hoa ẩm thực cố đô huyền thoại, nước lèo cay cay thơm ngát hương sả và mắm ruốc chưng.",
        "vung_mien": "Miền Trung",
        "vi_dac_trung": "Đậm, Cay",
        "cach_an": "Thêm sả ớt chưng sa tế đậm đà, ăn kèm hoa chuối bào nhuyễn, giá đỗ sống rổ rau thơm thơm.",
        "calo": "500 kcal / tô",
        "khau_phan": "1 tô đầy đủ",
        "protein": "28g",
        "carb": "55g",
        "fat": "16g",
        "thanh_phan": "Sợi bún to, thịt nạm bò bò tươi, chân giò heo, huyết heo mềm, chả cua Huế đặc trưng",
        "gia_trung_binh": "40.000 - 80.000 VNĐ",
        "thoi_diem_phu_hop": "Bữa sáng, trưa",
        "chi_so_suc_khoe": "⭐⭐⭐⭐☆",
        "khuyen_nghi": "Cung cấp nguồn protein và sắt vô cùng dồi dào cho cơ thể phục hồi năng lượng."
    },
    "Bun_Dau_mam_tom": {
        "ten_hien_thi": "Bún đậu mắm tôm",
        "mo_ta": "Sự kết hợp hoàn mỹ đầy cá tính ẩm thực Hà Thành giữa bún lá thanh mát, đậu rán giòn và chén mắm tôm sủi bọt ngập tắc.",
        "vung_mien": "Miền Bắc",
        "vi_dac_trung": "Đậm, Chua",
        "cach_an": "Đánh sủi bọt mắm tôm bằng nước tắc, đường và ớt xắt, gắp đậu hũ rán béo ngậy chấm ngập sâu vào nước mắm.",
        "calo": "600 kcal / phần",
        "khau_phan": "1 mẹt lớn đầy đủ",
        "protein": "25g",
        "carb": "50g",
        "fat": "28g",
        "thanh_phan": "Bún lá nhỏ cắt vuông, đậu phụ chiên rộp giòn, thịt ba chỉ luộc mỏng, chả cốm dẻo thơm, rau kinh giới",
        "gia_trung_binh": "35.000 - 80.000 VNĐ",
        "thoi_diem_phu_hop": "Bữa trưa bình dân",
        "chi_so_suc_khoe": "⭐⭐⭐☆☆",
        "khuyen_nghi": "Khá nhiều chất béo đến từ dầu chiên đậu và chả cốm, có thể điều chỉnh lượng ăn vừa phải."
    },
    "Bun_Rieu": {
        "ten_hien_thi": "Bún riêu",
        "mo_ta": "Món bún nước dân dã thơm ngon đậm đà làm bừng tỉnh vị giác nhờ vị chua thanh từ cà chua và cua đồng tươi giã.",
        "vung_mien": "Miền Bắc",
        "vi_dac_trung": "Đậm, Chua",
        "cach_an": "Hòa thêm một muỗng nhỏ mắm tôm Bắc đậm đà, vắt chanh tươi và thả thật nhiều rau muống chẻ xanh giòn.",
        "calo": "450 kcal / tô",
        "khau_phan": "1 tô nóng hổi",
        "protein": "22g",
        "carb": "55g",
        "fat": "12g",
        "thanh_phan": "Bún nhỏ, gạch cua đồng xào vàng óng, đậu phụ rán, cà chua đỏ mọng, dấm bỗng thơm nồng",
        "gia_trung_binh": "30.000 - 60.000 VNĐ",
        "thoi_diem_phu_hop": "Bữa sáng ấm áp, bữa trưa nhẹ nhàng",
        "chi_so_suc_khoe": "⭐⭐⭐⭐☆",
        "khuyen_nghi": "Nguồn cung cấp dồi dào canxi hữu cơ tự nhiên vô cùng tốt từ gạch cua."
    },
    "Bun_Thit_Nuong": {
        "ten_hien_thi": "Bún thịt nướng",
        "mo_ta": "Bún mát rượi hòa quyện cùng từng dải thịt heo nướng cháy cạnh thơm phức mùi sả tỏi băm thơm nức.",
        "vung_mien": "Miền Nam",
        "vi_dac_trung": "Đậm, Ngọt",
        "cach_an": "Chan đẫm chén nước mắm chua ngọt kẹo kẹo tỏi ớt lên bát bún, rắc thêm mỡ hành béo ngậy và đậu phộng rang giòn rồi trộn đều.",
        "calo": "500 kcal / tô",
        "khau_phan": "1 tô trộn đầy đủ",
        "protein": "25g",
        "carb": "60g",
        "fat": "15g",
        "thanh_phan": "Bún tươi sợi nhỏ, thịt heo nướng lò than xém thơm, rau xà lách băm dưa leo, đậu phộng rang giã dập",
        "gia_trung_binh": "35.000 - 70.000 VNĐ",
        "thoi_diem_phu_hop": "Bữa trưa, bữa chiều nhẹ nhàng",
        "chi_so_suc_khoe": "⭐⭐⭐⭐☆",
        "khuyen_nghi": "Độ cân bằng dinh dưỡng xuất sắc nhờ lượng rau xanh kèm bún luôn phong phú."
    },
    "Bun_ngan": {
        "ten_hien_thi": "Bún ngan",
        "mo_ta": "Hương vị Hà Nội tao nhã, thịt ngan luộc săn chắc chắc ngọt lịm chan ngập nước hầm xương thơm ngọt thanh dịu.",
        "vung_mien": "Miền Bắc",
        "vi_dac_trung": "Đậm, Thanh",
        "cach_an": "Ăn cùng măng muối chua cay, chấm thịt ngan vào đĩa nước mắm cốt tỏi ớt siêu ngon.",
        "calo": "480 kcal / tô",
        "khau_phan": "1 tô đầy đặn",
        "protein": "30g",
        "carb": "45g",
        "fat": "18g",
        "thanh_phan": "Bún, thịt ngan luộc ngọt, măng tươi xào, hành lá cắt nhỏ, nước dùng ninh từ xương ngan mỡ màng",
        "gia_trung_binh": "40.000 - 80.000 VNĐ",
        "thoi_diem_phu_hop": "Bữa ăn chính ấm áp",
        "chi_so_suc_khoe": "⭐⭐⭐⭐☆",
        "khuyen_nghi": "Nước dùng có chút mỡ béo tự nhiên ngọt thơm, có thể vắt chanh để dung hòa."
    },
    "Ca_Kho": {
        "ten_hien_thi": "Cá kho tộ",
        "mo_ta": "Món mặn cực kỳ đưa cơm trong mâm cơm Việt, từng khoanh cá kho đậm đà thơm cay nồng rắc tiêu đen sẫm.",
        "vung_mien": "Miền Nam",
        "vi_dac_trung": "Đậm, Ngọt",
        "cach_an": "Thưởng thức nóng cùng bát cơm trắng dẻo, rưới nước sốt cá kho ngọt ngọt mặn mặn chấm kèm dưa leo giòn rụm.",
        "calo": "250 kcal / phần",
        "khau_phan": "1 khay cá kho nhỏ (~100g)",
        "protein": "25g",
        "carb": "5g",
        "fat": "12g",
        "thanh_phan": "Cá lóc hoặc cá trắm tươi, nước mắm ngon, nước màu thốt nốt kẹo thơm, tiêu hạt nghiền, ớt trái",
        "gia_trung_binh": "30.000 - 70.000 VNĐ",
        "thoi_diem_phu_hop": "Bữa cơm trưa, tối ấm gia đình",
        "chi_so_suc_khoe": "⭐⭐⭐⭐⭐",
        "khuyen_nghi": "Giàu kẽm và protein chất lượng cao cùng chất béo Omega-3 tự nhiên tốt cho tim mạch."
    },
    "Canh_chua": {
        "ten_hien_thi": "Canh chua",
        "mo_ta": "Món canh giải nhiệt lý tưởng với vị chua từ me chín mọng hòa quyện nét ngọt thanh sông nước miền Tây Nam Bộ.",
        "vung_mien": "Miền Nam",
        "vi_dac_trung": "Chua, Ngọt",
        "cach_an": "Dùng nóng trong bữa cơm chính dọn kèm bún tươi, gắp thịt cá chấm đĩa nước mắm mặn nguyên chất cắt ớt xiêm.",
        "calo": "120 kcal / tô",
        "khau_phan": "1 tô lớn canh",
        "protein": "10g",
        "carb": "8g",
        "fat": "4g",
        "thanh_phan": "Cá lóc hoặc cá hú, me chín tươi lọc nước chua, dọc mùng bóp muối dẻo, thơm lát, đậu bắp, ngò ôm, ngò gai",
        "gia_trung_binh": "20.000 - 50.000 VNĐ",
        "thoi_diem_phu_hop": "Bữa ăn cơm gia đình",
        "chi_so_suc_khoe": "⭐⭐⭐⭐⭐",
        "khuyen_nghi": "Calo thấp vượt trội, cung cấp lượng nước giải nhiệt cùng dồi dào vitamin từ các loại rau quả xanh lành mạnh."
    },
    "Cao_lau": {
        "ten_hien_thi": "Cao lầu",
        "mo_ta": "Báu vật ẩm thực cổ Hội An đầy tự hào với sợi mì tro dai chắc rưới nước xốt rim thịt heo đậm đà khó cưỡng.",
        "vung_mien": "Miền Trung",
        "vi_dac_trung": "Đậm, Thanh",
        "cach_an": "Trộn thật đều cho sợi mì thấm đẫm xốt béo ngậy sệt sệt, rắc thêm ram chiên phồng giòn rụm và rau sống Trà Quế.",
        "calo": "450 kcal / tô",
        "khau_phan": "1 bát tô gỗ",
        "protein": "20g",
        "carb": "55g",
        "fat": "14g",
        "thanh_phan": "Sợi mì cao lầu ngâm nước tro, thịt ba chỉ heo rim xá xíu, ram da heo chiên giòn, rau sống thảo mộc đặc sản",
        "gia_trung_binh": "35.000 - 70.000 VNĐ",
        "thoi_diem_phu_hop": "Bữa ăn trưa ấm áp",
        "chi_so_suc_khoe": "⭐⭐⭐⭐☆",
        "khuyen_nghi": "Món ăn độc đáo bổ dưỡng, nên ăn kèm rau húng để kích thích tiêu hóa."
    },
    "Cha gio": {
        "ten_hien_thi": "Chả giò",
        "mo_ta": "Món cuốn chiên giòn có lớp vỏ rụm mỏng giòn bọc ngoài phần nhân nấm mèo thịt băm đượm mùi tiêu xay thơm phức.",
        "vung_mien": "Miền Nam",
        "vi_dac_trung": "Đậm, Béo",
        "cach_an": "Cuốn ngập chặt chả giò nóng giòn cùng lá rau xà lách xanh mát, rau húng lũi thơm rổi chấm mắm chua ngọt pha tỏi ớt băm.",
        "calo": "120 kcal / cuốn",
        "khau_phan": "1 cuốn to",
        "protein": "4g",
        "carb": "10g",
        "fat": "7g",
        "thanh_phan": "Bánh tráng mỏng cuốn, nạc vai heo băm giã nhuyễn, miến dong, mộc nhĩ, cà rốt thái chỉ, lòng đỏ trứng",
        "gia_trung_binh": "5.000 - 15.000 VNĐ",
        "thoi_diem_phu_hop": "Khai vị, ăn kèm bún thịt nướng",
        "chi_so_suc_khoe": "⭐⭐⭐☆☆",
        "khuyen_nghi": "Hàm lượng dầu béo chiên rán ngập chảo tương đối lớn, nên thưởng thức lượng vừa phải vừa miệng."
    },
    "Chao long": {
        "ten_hien_thi": "Cháo lòng",
        "mo_ta": "Món cháo thơm ngậy nấu từ nước luộc lòng heo béo ngọt lịm kết hợp huyết lòng sánh nâu, dọn kèm đĩa lòng tươi thập cẩm.",
        "vung_mien": "Miền Nam",
        "vi_dac_trung": "Đậm, Béo",
        "cach_an": "Ăn thật nóng, bỏ thêm giá sống giòn, rắc thật nhiều tiêu bột đen, hành lá xắt nhỏ và vắt chút nước cốt chanh chua.",
        "calo": "350 kcal / tô",
        "khau_phan": "1 tô ngập tràn lòng",
        "protein": "18g",
        "carb": "35g",
        "fat": "12g",
        "thanh_phan": "Gạo tẻ rang vàng, nước xương hầm ngọt, lòng non lòng heo, huyết, tim heo dồi sụn tỏi ớt",
        "gia_trung_binh": "25.000 - 50.000 VNĐ",
        "thoi_diem_phu_hop": "Ăn sáng ấm bụng, ăn đêm mát trời",
        "chi_so_suc_khoe": "⭐⭐⭐☆☆",
        "khuyen_nghi": "Nội tạng heo giàu đạm dồi dào nhưng chứa lượng mỡ Cholesterol cao, hạn chế dùng thường xuyên đối với người bệnh khớp."
    },
    "Com chien": {
        "ten_hien_thi": "Cơm chiên",
        "mo_ta": "Đĩa cơm chiên xốp vàng ruộm giòn giòn hạt gạo săn, trộn lẫn xúc xích, đậu Hà Lan thơm tơi ngọt mọng ngọt.",
        "vung_mien": "Miền Nam",
        "vi_dac_trung": "Đậm, Béo",
        "cach_an": "Dùng nóng bốc khói ấm, chan thêm vài giọt xì dầu nước tương ớt cắt cay tê nồng tăng dậy hương cơm thơm.",
        "calo": "550 kcal / phần",
        "khau_phan": "1 đĩa cơm đầy đặn",
        "protein": "18g",
        "carb": "65g",
        "fat": "20g",
        "thanh_phan": "Cơm nguội ráo khô hạt cơm bóp tơi, trứng vịt nghệ, lạp xưởng thái nhỏ, đậu bắp xanh, cà rốt",
        "gia_trung_binh": "30.000 - 60.000 VNĐ",
        "thoi_diem_phu_hop": "Bữa ăn chính ấm bụng",
        "chi_so_suc_khoe": "⭐⭐⭐☆☆",
        "khuyen_nghi": "Giàu calo dồi dào thúc đẩy thể lực chuyển động mạnh mẽ thích hợp sau ngày dài dốc sức mệt mỏi."
    },
    "Com tam": {
        "ten_hien_thi": "Cơm tấm",
        "mo_ta": "Món ăn quốc dân lừng danh Sài Thành thơ mộng, hạt cơm tấm bùi mịn, sườn nướng mỡ hành tỏa mùi thơm phức.",
        "vung_mien": "Miền Nam",
        "vi_dac_trung": "Đậm, Ngọt",
        "cach_an": "Rưới đều bát nước mắm ngọt kẹo cay nhẹ phủ đẫm sườn cốt lết heo, bì dẻo và chả trứng béo thơm nồng nàn.",
        "calo": "650 kcal / phần",
        "khau_phan": "1 đĩa cơm đầy đủ sườn bì chả",
        "protein": "32g",
        "carb": "68g",
        "fat": "25g",
        "thanh_phan": "Hạt tấm dẻo, sườn cốt lết nướng than quết mật, thính gạo bì mềm mỏng, chả trứng chưng vàng",
        "gia_trung_binh": "35.000 - 80.000 VNĐ",
        "thoi_diem_phu_hop": "Ăn sáng tràn lực lượng, ăn tối",
        "chi_so_suc_khoe": "⭐⭐⭐☆☆",
        "khuyen_nghi": "Calo dồi dào cực tốt cho hoạt động thể chất dã ngoại tiêu tốn calo lớn."
    },
    "Goi cuon": {
        "ten_hien_thi": "Gỏi cuốn",
        "mo_ta": "Món ăn thanh đạm nằm trong top các món lành mạnh nhất thế giới, cuốn bánh tráng mỏng lộ rõ tôm luộc đỏ tươi rực rỡ.",
        "vung_mien": "Miền Nam",
        "vi_dac_trung": "Thanh, Béo",
        "cach_an": "Chấm sâu gỏi cuốn vào đĩa tương đậu phộng chưng bơ béo ngậy thơm nồng dập mẩy tỏi ớt phi băm nhuyễn.",
        "calo": "90 kcal / cuốn",
        "khau_phan": "1 cuốn dài vừa miệng",
        "protein": "6g",
        "carb": "10g",
        "fat": "2g",
        "thanh_phan": "Bánh tráng dẻo mỏng dai nhẹ, tôm đất thẻ luộc bóc vỏ xẻ đôi, ba chỉ heo chín mỏng béo ngọt, bún, rau hẹ xanh tươi",
        "gia_trung_binh": "5.000 - 15.000 VNĐ",
        "thoi_diem_phu_hop": "Ăn kiêng, bữa xế lành mạnh nhẹ dạ",
        "chi_so_suc_khoe": "⭐⭐⭐⭐⭐",
        "khuyen_nghi": "Calo cực thấp sạch dầu mỡ tuyệt đối cho cơ thể dẻo dai khỏe khoắn tràn đầy vitamin tự nhiên lành."
    },
    "Hu tieu": {
        "ten_hien_thi": "Hủ tiếu",
        "mo_ta": "Linh hồn ẩm thực phương Nam dịu ngọt, nước lèo xương ống ninh trong veo rắc tóp mỡ vàng óng ánh.",
        "vung_mien": "Miền Nam",
        "vi_dac_trung": "Đậm, Thanh",
        "cach_an": "Thưởng thức nóng rắc tỏi phi vàng giòn, ăn kèm giá sống hẹ, xịt tương đen bơ nồng ấm say lòng.",
        "calo": "430 kcal / tô",
        "khau_phan": "1 tô hủ tiếu nước đầy đặn",
        "protein": "22g",
        "carb": "52g",
        "fat": "10g",
        "thanh_phan": "Sợi hủ tiếu dai dai đặc thù Sa Đéc, nước hầm ngọt mát từ xương mực khô heo, thịt băm, tôm ngọt",
        "gia_trung_binh": "35.000 - 70.000 VNĐ",
        "thoi_diem_phu_hop": "Ăn sáng, ăn đêm bừng dạ",
        "chi_so_suc_khoe": "⭐⭐⭐⭐☆",
        "khuyen_nghi": "Độ cân đối tốt cho tim, giàu carbohydrate cung cấp năng lượng hoạt động."
    },
    "Mi quang": {
        "ten_hien_thi": "Mì Quảng",
        "mo_ta": "Món ăn thân thương đậm tình Quảng Nam, sợi mì bản to rắc bánh tráng nướng vụn bùi giòn rụm bùi.",
        "vung_mien": "Miền Trung",
        "vi_dac_trung": "Đậm, Cay",
        "cach_an": "Trộn thật lực cho đều đặn cùng chút ít nước nhân béo ngậy rim kẹo, bẻ vụn bánh tráng dừa gắp kèm rau cải con cay mát nồng nàn.",
        "calo": "470 kcal / tô",
        "khau_phan": "1 tô mì xốt rắc đậu phộng",
        "protein": "24g",
        "carb": "55g",
        "fat": "14g",
        "thanh_phan": "Sợi mì Quảng vàng từ nghệ tươi chín dẻo, tôm rim mặn ngọt đậm tỏi, thịt ba chỉ, bánh tráng nướng vàng ruộm dừa giòn",
        "gia_trung_binh": "35.000 - 70.000 VNĐ",
        "thoi_diem_phu_hop": "Bữa trưa, bữa chiều",
        "chi_so_suc_khoe": "⭐⭐⭐⭐☆",
        "khuyen_nghi": "Nên ăn kèm ngò gai búp chuối thái mỏng tăng dồi dào chất xơ kích hoạt hoạt động dạ dày thanh sạch."
    },
    "Nem chua": {
        "ten_hien_thi": "Nem chua",
        "mo_ta": "Món nhắm cá tính nổi tiếng từ vùng đất Thanh Hóa, thịt heo tươi lên men sinh học tự nhiên chua cay tê lưỡi hương tỏi ớt.",
        "vung_mien": "Miền Trung",
        "vi_dac_trung": "Chua, Cay",
        "cach_an": "Bóc nhẹ vỏ lá chuối rải tỏi xắt mỏng, chấm cùng chút tương ớt tỏi ngọt lịm kích nổ vị giác hoàn chỉnh mộc mạc ngon tột độ.",
        "calo": "70 kcal / cái",
        "khau_phan": "1 cái nem nhỏ gói chặt",
        "protein": "5g",
        "carb": "2g",
        "fat": "4g",
        "thanh_phan": "Nạc mông heo nóng giã nhuyễn mọng nước, bì heo cạo tơ mỏng dai dòn dẻo, tỏi ta dập mỏng lá đinh lăng",
        "gia_trung_binh": "3.000 - 8.000 VNĐ",
        "thoi_diem_phu_hop": "Ăn chơi xế chiều mát mẻ",
        "chi_so_suc_khoe": "⭐⭐⭐☆☆",
        "khuyen_nghi": "Nên tìm kiếm Nem từ các cơ sở chế biến thực phẩm uy tín sạch sẽ tuyệt đối đảm bảo lên men sạch."
    },
    "Pho": {
        "ten_hien_thi": "Phở",
        "mo_ta": "Biểu tượng văn hóa ẩm thực trường tồn đất Việt, nước dùng trong vắt ninh tủy xương bò thơm nồng hồi quế ấm.",
        "vung_mien": "Miền Bắc",
        "vi_dac_trung": "Đậm, Thanh",
        "cach_an": "Thưởng thức bốc khói cay nóng giòn, thêm chút dấm tỏi nồng nàn thơm nức, tương ớt đỏ cay xè kèm bánh quẩy vàng béo giòn giòn dẻo.",
        "calo": "450 kcal / tô",
        "khau_phan": "1 tô phở tái chín gầu bò thơm phức",
        "protein": "25g",
        "carb": "50g",
        "fat": "12g",
        "thanh_phan": "Bánh phở dẻo mềm dẻo dai nhẹ, nước dùng tủy ống bò ninh ròng suốt 12 tiếng thơm, thịt nạm bò mềm gầu béo giòn",
        "gia_trung_binh": "35.000 - 80.000 VNĐ",
        "thoi_diem_phu_hop": "Ăn sáng thanh cảnh ấm áp, tối",
        "chi_so_suc_khoe": "⭐⭐⭐⭐⭐",
        "khuyen_nghi": "Cực phẩm bồi dưỡng bổ xương cơ, tái cấu trúc hoạt động tinh thần tỉnh táo bừng rực sảng khoái."
    },
    "Sup_cua": {
        "ten_hien_thi": "Súp cua",
        "mo_ta": "Chén súp đặc sệt giàu chất đạm dồi dào cua biển mọng nước ngọt ngào mát lành từ trứng bắc thảo bùi ngọt đậm.",
        "vung_mien": "Miền Nam",
        "vi_dac_trung": "Đậm, Thanh",
        "cach_an": "Ăn bằng thìa lúc còn nóng nguyên độ sánh sệt mượt, nhỏ thêm giọt dầu mè ngò rí và một ít hạt tiêu xay sực mùi.",
        "calo": "180 kcal / chén",
        "khau_phan": "1 chén đầy ăm ắp nhân ngọt",
        "protein": "12g",
        "carb": "15g",
        "fat": "6g",
        "thanh_phan": "Thịt ghẹ cua biển xé mỏng ngọt, trứng bắc thảo bùi béo bùi dẻo, bắp hạt vàng dẻo, bột năng nấu quện nhuyễn mịn",
        "gia_trung_binh": "20.000 - 45.000 VNĐ",
        "thoi_diem_phu_hop": "Ăn nhẹ xế chiều êm nhẹ bụng",
        "chi_so_suc_khoe": "⭐⭐⭐⭐☆",
        "khuyen_nghi": "Món ăn tuyệt vời hồi sức người ốm mệt cần nhiều đạm bổ dễ xoa bóp cơ quan tiêu hóa."
    },
    "Xoi xeo": {
        "ten_hien_thi": "Xôi xéo",
        "mo_ta": "Màu vàng rực từ củ nghệ tự nhiên của gạo nếp dẻo thơm nồng giòn tan hành khô phi thơm nức phố cổ.",
        "vung_mien": "Miền Bắc",
        "vi_dac_trung": "Đậm, Béo",
        "cach_an": "Ăn khi nắm xôi dẻo nếp còn bốc khói gói kín rơm lá chuối, xắt những lát đậu xanh dẻo mịn tan đầu lưỡi rưới mỡ màng thơm béo.",
        "calo": "420 kcal / phần",
        "khau_phan": "1 gói gói lá chuối đầy hành phi",
        "protein": "10g",
        "carb": "75g",
        "fat": "8g",
        "thanh_phan": "Nếp cái dẻo ủ nghệ thơm mượt dẻo dai, đậu xanh đồ dẻo giã nắm tơi nhuyễn rưới mỡ heo, hành củ đỏ chưng phơi phi giòn rụm",
        "gia_trung_binh": "15.000 - 35.000 VNĐ",
        "thoi_diem_phu_hop": "Ăn sáng no lâu bừng nhiệt huyết ngày mới",
        "chi_so_suc_khoe": "⭐⭐⭐☆☆",
        "khuyen_nghi": "Nguồn tinh bột và năng lượng dồi dào tuyệt đối, thích hợp cho người chuẩn bị lao động trí óc căng thẳng dã ngoại ngày dài."
    }
}


def get_food_info(class_name: str) -> dict:
    return FOOD_DB.get(
        class_name,
        {
            "ten_hien_thi": class_name,
            "mo_ta": "Chưa có thông tin chi tiết cho món này.",
            "vung_mien": "Không rõ",
            "vi_dac_trung": "Thanh",
            "cach_an": "Ăn trực tiếp.",
            "calo": "Không rõ",
            "khau_phan": "Không rõ",
            "protein": "Không rõ",
            "carb": "Không rõ",
            "fat": "Không rõ",
            "thanh_phan": "Không rõ",
            "gia_trung_binh": "Không rõ",
            "thoi_diem_phu_hop": "Không rõ",
            "chi_so_suc_khoe": "Chưa đánh giá",
            "khuyen_nghi": "Không có khuyến nghị."
        },
    )


def _extract_calories(calo_str: str) -> int:
    import re
    if not calo_str:
        return 0
    try:
        match = re.search(r'\d+', calo_str)
        if match:
            return int(match.group())
    except:
        pass
    return 0


def get_similar_calorie_foods(current_class_name: str, limit: int = 3) -> list:
    current_info = FOOD_DB.get(current_class_name)
    if not current_info or "calo" not in current_info:
        return []
    
    current_cal = _extract_calories(current_info["calo"])
    if current_cal == 0:
        return []
    
    candidates = []
    for name, info in FOOD_DB.items():
        if name == current_class_name:
            continue
        cal = _extract_calories(info.get("calo", ""))
        if cal > 0:
            diff = abs(current_cal - cal)
            candidates.append({
                "class_name": name,
                "ten_hien_thi": info["ten_hien_thi"],
                "calo": info["calo"],
                "diff": diff,
                "diff_signed": cal - current_cal
            })
            
    candidates.sort(key=lambda x: x["diff"])
    return candidates[:limit]